### PR TITLE
go-fuzz-build: respect GO111MODULE if set

### PR DESCRIPTION
**Pull request by josharian**
This is an alternative to #271.

Updates #195

cc @mvdan @yevgenypats @dvyukov

### CODE REVIEW

**Comment by yevgenypats** [comment]
@josharian looks like it fails the CI.

**Comment by josharian** [comment]
Ah, the CI failed because there's a CI configuration that explicitly sets GO111MODULE=on. Which doesn't work for our tests. @thepudds what do you think the right thing to do here is?

**Comment by yevgenypats** [comment]
I'm in favour of merging https://github.com/dvyukov/go-fuzz/pull/271 asap as it doesn't affect the current users and tests at all and it remove the block for a lot of users that are waiting for long time for this one:

https://twitter.com/fuzzitdev/status/1169137825142452225
https://www.reddit.com/r/golang/comments/dc98vv/how_to_fuzz_go_code_with_gofuzz_continuously/
https://twitter.com/search?q=go-fuzz%20modules&src=typed_query

**Comment by josharian** [comment]
I’m closing this in favor of #274, which I will review ASAP, probably within the next few days.

**Pull request closed without merging**
