### PR TITLE
Add execution duration flag

### PR DESCRIPTION
**Pull request by klauspost**
Add flag for automatic shutdown after a specified duration.

It seems there can be advantages of restarting fuzzing at regular intervals as seen in #257

Also it can be useful to run fuzz tests for a short period to check for regressions.

To facilitate this, add a `-duration` parameter. After the fuzzer has been running this duration it will do a regular exit.

This will always exit with code 0. It could make sense to exit with non-zero if there it one or more crashers.

### CODE REVIEW

**Comment by klauspost** [comment]
Yeah, you are correct that this is a "pessimistic" PR, but it allows me to run the fuzzer in a more productive way right now.

I don't have `timeout` available on Windows, where I mainly run my fuzz tests, so a simple script like this works perfectly:

```
:LOOP
go-fuzz -duration=1h -bin=fuzz-build.zip -workdir=%CORPUS% -procs=%PROCS%
GOTO LOOP
```

**Comment by dvyukov** [comment]
This should have several implementations ;)
https://www.google.com/search?q=timeout+command+for+windows+in+golang

**Comment by klauspost** [comment]
Yeah, I guess that would do it as well. 👍

**Comment by klauspost** [comment]
I made [this timeout program](https://github.com/klauspost/compress-fuzz/blob/master/timeout.go), which does what I'm looking for. Leaving it here in case it could be useful for others.

**Pull request closed without merging**
