### PR TITLE
Vendor dependencies

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**

### CODE REVIEW

**Comment by dvyukov** [comment]
Is it for go tool vendoring? Frankly I don't understand what happens here. @davecheney can you please vet this?

**Comment by Thomasdezeeuw** [comment]
I added the repo's manually using `git submodule add`, but now you can run `go install` without needing to download any extra packages.

**Comment by dvyukov** [comment]
I don't understand. Where did you add a repo? What repo? And why did you need to add it?
Currently I can run `go ge`t and it will download and build everything. Though, it can download a broken version of a dependency.

**Comment by Thomasdezeeuw** [comment]
Using the repo at a fixed commit makes sure the build will keep working and also cleanups the `src` directory in `$GOPATH`.

**Comment by ssoroka** [comment]
Nobody likes git submodules. http://somethingsinistral.net/blog/git-submodules-are-probably-not-the-answer/ :D

**Comment by Thomasdezeeuw** [comment]
Seeing that this isn't going to happend, I'll close this.

**Pull request closed without merging**
