### PR TITLE
go-fuzz-build: cannot find package "go-fuzz-dep" #320

### PR DESCRIPTION
**Pull request by hidu**

### CODE REVIEW

**Comment by disconnect3d** [comment]
@dvyukov @josharian can this be merged? it makes go-fuzz/go-fuzz-build compilation succeed on latest Go versions or/and in IDEs like Goland.

**Comment by josharian** [comment]
@thepudds what do you think?

**Comment by thepudds** [comment]
Hi @hidu, thanks for sending this PR. 

I'm not sure if it is the right fix though? I suspect it might workaround the immediate error you were seeing, but I wonder if this fix masks that the wrong GOROOT is still being used. I suspect with this fix, it is not instrumenting the standard library properly, but to be honest, I haven't looked at the suggested change closely enough, so that worry might be off base.

Stepping back, though, I wonder if there is a simpler solution that might work for you. See my comment [here](https://github.com/dvyukov/go-fuzz/issues/320#issuecomment-1001179584) on the related issue.

**Comment by thepudds** [comment]
Hi @disconnect3d, when you say this PR is needed to work with "latest Go versions or/and in IDEs like Goland", are you referring to whether or not go-fuzz is a module itself?

If so, one approach is to work in GOPATH mode if hacking on go-fuzz itself. See some related comments in #332.

If you are not referring to issues arising from whether or not go-fuzz is a module itself, can you expand a bit more on what issues you are seeing? Does it seem to be the same problem described by @hidu in #320?

FWIW, go-fuzz works reasonably well for me with latest Go versions. I don't use Goland, though.

**Comment by wulie** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Pull request closed without merging**
