### PR TITLE
gogo protobuf issue 86 fixed

### PR DESCRIPTION
**Pull request by awalterschulze**
gogo protobuf issue 86 fixed

### CODE REVIEW

**Comment by dvyukov** [comment]
@awalterschulze What was the test?
I expect it to be profitable to compare goprotobuf and gogoprotobuf side-by-side:
 - both success/fail on the same input
 - one can deserialize output of another
 - maybe compare output of serialization
That can find more bugs in both and ensure full compatibility.
@dgryski

**Comment by awalterschulze** [comment]
I created this repo for testing gogoprotobuf against goprotobuf.
https://github.com/gogo/harmonytests
This way gogoprotobuf does not depend on anything, but I still get those tests to see if gogoprotobuf and goprotobuf are working in harmony ;)

**Comment by awalterschulze** [comment]
For a test of the fuzzing issue I created my own little fuzzer that is generated with each proto Marshaling test.
https://github.com/gogo/protobuf/commit/8edb24c179ed858a38f18920d9005c2dde05ec17

testgen: generates a random protocol buffer instance using populate and then marshal and unmarshals the protocol buffer and checks that the input is equal to the output.

populate: generates a function that randomly populates a protocol buffer message.

Before comparing the two protocol buffers I also totally fuzz the original buffer to make sure that all bytes were copied and not referenced.

After comparison I fuzz a copy of the original data, just a little bit and very naively.
Then I try unmarshaling again and check that the code does not panic, which is the bug that was found.

**Comment by awalterschulze** [comment]
I don't think I am comparing the marshaled byte slice sizes in the harmony tests.
What I do, do is I compare the output of the Size() int method with proto.Size() which is basically still the original goprotobuf implementation.  I also compare these results to the actual size of the marshaled byte slice.  This is done in the generated tests, for example here:
https://github.com/gogo/protobuf/blob/master/test/thetestpb_test.go#L8346

**Comment by awalterschulze** [comment]
It was impossible to develop gogoprotobuf without comparing it side by side to goprotobuf.
i.e. very profitable.
The especially hard part was developing the unsafe code for structures with fields without pointers.  This is only used if you enable fields without pointers and don't enable the generated marshaling and unmarshaling code.
I basically have no idea what I did there, but the tests say it is working and go vet is not complaining.
That code is the main reason why I wrote so many tests.

**Comment by awalterschulze** [comment]
I hope I have answered all your questions :)
PS
Thanks for writing a tool that found a bug :)

**Comment by dvyukov** [comment]
@awalterschulze harmonytests does not use go-fuzz, right?
Did you compare the two implementations side-by-side in the go-fuzz test?

**Comment by awalterschulze** [comment]
no, no

**Comment by awalterschulze** [comment]
How would you do that, though?

**Comment by dvyukov** [comment]
Something along the lines of:

```go
func Fuzz(data []byte) int {
  m1 := new(MyStruct)
  err1 := goprotobuf.Decode(m1, data)
  m2 := new(MyStruct)
  err2 := gogoprotobuf.Decode(m2, data)
  if (err1 == nil) != (err2 != nil) {
    panic("decoders disagree")
  }
  if !DeepEqual(m1, m2) {
    panic("decoders disagree")
  }
  data1, err1 := goprotobuf.Encode(m1)
  if err1 != nil {
    panic(err1)
  }
  data2, err2 := gogoprotobuf.Encode(m2)
  if err2 != nil {
    panic(err2)
  }
  if !bytes.Equal(data1, data2) {
    panic("decoders disagree")
  }
  // or if Encode output differs by design, then check that
  // they decode output of another encoder:
  if err := goprotobuf.Decode(m1, data2); err != nil {
    panic(err)
  }
  if err := gogoprotobuf.Decode(m1, data1); err != nil {
    panic(err)
  }
}
```

Plus any other cross-checks that you can think of.

**Comment by awalterschulze** [comment]
Ok but if the data is fuzzed you will mostly get errors returned?

You would also need to generate this test for different types of structs.
They will then need to be in different packages so that there is only one Fuzz function.
Well you could probably have one Fuzz function call them all with the same bytes, but then you'll need to add all the generated functions to the same function, which falls a little outside of the generation model of protocol buffers, where each message is generated on its own.

**Comment by dvyukov** [comment]
> Ok but if the data is fuzzed you will mostly get errors returned?

Yes and no. First, if you can test 100'000 cases per second and correct inputs are only 0.1% and you run for a day, you still get pretty huge number of correct inputs. Second, correct inputs give larger coverage so fuzzer will prefer them over incorrect ones.

> You would also need to generate this test for different types of structs.

Take a look at my test for protobuf:
https://github.com/dvyukov/go-fuzz/tree/master/examples/protobuf
I would expect that it should be possible to plug gogoprotobuf into this test as well.

**Comment by awalterschulze** [comment]
True

The easiest way would probably be to simply replace 
```
protoc --go_out=. examples/protobuf/pb/gen.proto
```
with each of the following:
For almost no changes, but using the gogo/protobuf/proto library instead of golang/protobuf/proto
```
protoc --gogo_out=. examples/protobuf/pb/gen.proto
```
For having generated marshaling and unmarshaling fuctions, but still importing golang/protobuf/proto
```
protoc --gofast_out=. examples/protobuf/pb/gen.proto
```
Same but using the gogo/protobuf/proto library
```
protoc --gogofast_out=. examples/protobuf/pb/gen.proto
```
These might cause some problems, since using nullable=false has different semantics.
```
protoc --gogofaster_out=. examples/protobuf/pb/gen.proto
protoc --gogoslick_out=. examples/protobuf/pb/gen.proto
```

PS
Someone has just reported a bug that gofast does not work with required fields, so this is something I should still fix asap.

**Comment by awalterschulze** [comment]
I remember looking at those tests.  The messages are very small and they don't nearly cover all possibilities, but they have already found many bugs, so who am I to judge.

**Comment by awalterschulze** [comment]
Ok that required bug is fixed now.

**Comment by awalterschulze** [comment]
Ok I finally got some time and created this.
https://github.com/gogo/fuzztests
I generate the new function list and the corpus, that way you only need to add a message definition to get more tests.
I think might already be finding some bugs with my very simple Fuzz function.
I'll investigate more tomorrow, but I am too excited so I thought I'd let you know a little prematurely.

**Comment by dvyukov** [comment]
So you already got some reports out of that test?

**Comment by awalterschulze** [comment]
Most of the errors are wrong wireType errors, seems golang/protobuf is a bit more permissive about wrong wireTypes than my generated code, but I still have to double check.
A very small amount of protobufs are also unmarshaled using golang/protobuf, but my generated code returns an Unexpected EOF.  These seem the most interesting.
I suspect after fixing these I might find others.

I have to say go-fuzz looks very impressive so far.
Have you thought about using this almost like QuickCheck?
I could have some serialized protobuf as my corpus and only return a score of 1 when it successfully unmarshals.
Then I could use these fields as input parameters to a function and define some properties in fuzz.
Although it is probably not a good fit for minimizing the parameters and concurrency tests or am I wrong?

**Comment by awalterschulze** [comment]
I have created a few manual tests so I can start prodding a bit deeper.
https://github.com/gogo/fuzztests/blob/master/crashers_test.go

**Comment by awalterschulze** [comment]
Ok it seems that for unrecognized fields weird wireTypes are sometimes just not included in the resulting protobuf message, so when it is marshaled again it returns a different byte slice.
The generated code typically returns and error in this case, but is definitely not immune.
But for all cases where golang/protobuf does not have an idempotent error, gogoprotobuf also does not have any error.

**Comment by dvyukov** [comment]
> Have you thought about using this almost like QuickCheck?

If I correctly understand you, you want this:
https://github.com/dvyukov/go-fuzz/issues/65
right?

**Pull request merged**
