### PR TITLE
versifier: kv of list, list of kv, kv num

### PR DESCRIPTION
**Pull request by rlmcpherson**
This small improvement to the versifier adds support for kv of lists and
list of kv based on discussion in #62. kv with numeric values are also
supported.

### CODE REVIEW

**Comment by dvyukov** [comment]
Generally this looks good to me.
But versifier becomes more and more complex and it is difficult to track how changes affect parsing. In particular I am not sure that parsing of some constructs does not degrade with this change. Can you think of any way of writing real tests for versifier? Tests that ensure that particular inputs gets parsed in a particular way? That would help to assess changes like this.

**Comment by dgryski** [comment]
Stringify as s-expressions? With a standard representation writing tests becomes easy.

**Comment by dvyukov** [comment]
Agree. Some canonical serialization format along the lines of (speculating about actual format):
```
KV("foo", "=", LIST(NUM("1"), NUM("2"), NUM("3")))
```
looks simple and efficient.

**Comment by rlmcpherson** [comment]
Agreed. I wrote some basic self-verifying tests as part of making this change but wasn't happy with the result. A better stringification of verse nodes would help. 

Tests could also verify the verse nodes directly, although I'm not sure it's an advantageous approach.

**Comment by rlmcpherson** [comment]
Is there any reason to keep the Node Print methods as they are or can they be changed to print themselves as s-expressions?

**Comment by dvyukov** [comment]
> I wrote some basic self-verifying tests as part of making this change but wasn't happy with the result.

That's already better than not knowing that something is broken.
You don't need to fix everything in this change. If you just write a test that shows that something is parsed suboptimally and leave a comment, that would be enough.

> Is there any reason to keep the Node Print methods as they are or can they be changed to print themselves as s-expressions?

I used Print only for manually debugging during initial development. So, yeah, you can change it.

**Comment by odeke-em** [comment]
How's it going @rlmcpherson?

**Comment by AlekSi** [comment]
@rlmcpherson Please note that go-fuzz repository history was rewritten to reduce total repository size and download time. The easiest migration path for this PR is to `git cherry-pick` commits on top of current `master`.

**Comment by josharian** [comment]
It looks like this has been abandoned. I'd love to be wrong. If so, please open a new PR against the current master branch. Thanks!

Oh, and if anyone else wants to pick this up, the easiest way to start is probably by just cherry-picking this commit: https://github.com/dvyukov/go-fuzz/pull/70/commits/1d094b330e25c876d57f0e0b1daa9656d356e8a2

**Pull request closed without merging**
